spring:
  batch:
    job:
      names: ${job.name:NONE} #edit configuration -> CLI -> --spring.batch.job.names=helloWorldJob 설정 해줘야 한다.
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
